### PR TITLE
Remove `xfail` mark from `tests/cli/test_main.py::test_commands_docs_links`

### PR DESCRIPTION
**Pull request by aguschin**
Can do now since docs are released.

### CODE REVIEW

**Comment by madhur-tandon** [comment]
The test fails though, what is it for?

**Comment by aguschin** [comment]
In the `mlem cmd -h` we have an URL to the docs. The test checks that the links exist on mlem.ai

e.g.

```
$ mlem clone -h                                                                                                         101ms

 Usage: mlem clone [options] uri target

 Copy a MLEM Object from `uri` and saves a copy of it to `target` path.
 Documentation: <https://mlem.ai/doc/command-reference/clone>

╭─ Arguments ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *    uri         TEXT  URI to object you want to clone [default: None] [required]                                                                    │
│ *    target      TEXT  Path to store the downloaded object. [default: None] [required]                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --project              -p      path       Path to MLEM project [default: (none)]                                                                     │
│ --rev                          commitish  Repo revision to use [default: (none)]                                                                     │
│ --target-project,--tp          path       Project to save target to [default: (none)]                                                                │
│ --help                 -h                 Show this message and exit.                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by aguschin** [comment]
Not sure what's the reason for fail - it works on my machine (TM). Interesting that no commands have documentation link - like `serve` for example. It should mean that `$ mlem serve -h` run in CI doesn't have docs link in output. Strange, what could be the reason? 🤔

**Review by omesser — APPROVED** [review]

**Comment by aguschin** [comment]
Thanks @mike0sv. Looks good to me. You have to approve PR (I can't) and then you can merge this.

**Review by mike0sv — APPROVED** [review]

**Pull request merged**
