### PR TITLE
Remove standard signature from models and move it to servers

### LINKED ISSUE #445: De-duplicate methods in `.mlem` model metafile
If we TAL at metafile, we can see the duplication of methods as `predict` + `sklearn_predict`, `predict_proba` + `sklearn_predict_proba`. The reason to introduce them was to give a common interface to models from different frameworks. E.g. sklearn's `predict` and someotherframework's `get_prediction` would have the same endpoint once deployed.

I think we shouldn't duplicate them here. It should be configurable on the server level. This will make future changes depend not on the time when you saved the model, but on the MLEM version.

```yaml
artifacts:
  data:
    hash: 5a38e5d68b9b9e69e9e894bcc9b8a601
    size: 163651
    uri: rf
model_type:
  methods:
    predict:
      args:
        - name: data
          type_:
            columns:
              - sepal length (cm)
              - sepal width (cm)
              - petal length (cm)
              - petal width (cm)
            dtypes:
              - float64
              - float64
              - float64
              - float64
            index_cols: []
            type: dataframe
      name: predict
      returns:
        dtype: int64
        shape:
          - null
        type: ndarray
    predict_proba:
      args:
        - name: data
          type_:
            columns:
              - sepal length (cm)
              - sepal width (cm)
              - petal length (cm)
              - petal width (cm)
            dtypes:
              - float64
              - float64
              - float64
              - float64
            index_cols: []
            type: dataframe
      name: predict_proba
      returns:
        dtype: float64
        shape:
          - null
          - 3
        type: ndarray
    sklearn_predict:
      args:
        - name: X
          type_:
            columns:
              - sepal length (cm)
              - sepal width (cm)
              - petal length (cm)
              - petal width (cm)
            dtypes:
              - float64
              - float64
              - float64
              - float64
            index_cols: []
            type: dataframe
      name: predict
      returns:
        dtype: int64
        shape:
          - null
        type: ndarray
    sklearn_predict_proba:
      args:
        - name: X
          type_:
            columns:
              - sepal length (cm)
              - sepal width (cm)
              - petal length (cm)
              - petal width (cm)
            dtypes:
              - float64
              - float64
              - float64
              - float64
            index_cols: []
            type: dataframe
      name: predict_proba
      returns:
        dtype: float64
        shape:
          - null
          - 3
        type: ndarray
  type: sklearn
object_type: model
requirements:
  - module: sklearn
    version: 1.1.2
  - module: numpy
    version: 1.22.4
  - module: pandas
    version: 1.5.0
```

### PR DESCRIPTION
**Pull request by mike0sv**
WIP
You can check this with code (assuming you have a mlem model at "sklearn")

NOTE: THIS WAS A WIP EXAMPLE, IT DOESNT WORK IN CURRENT MLEM VERSION

```python
from mlem.api import serve
from mlem.contrib.fastapi import FastAPIServer
from mlem.core.metadata import load_meta
from mlem.core.model import Argument, Signature
from mlem.core.objects import MlemModel
from mlem.runtime.interface import InterfaceDescriptor


def main():
    serve("sklearn", "fastapi", standardize=True)
    #
    serve("sklearn", "fastapi", standardize=False)

    model = load_meta("sklearn", force_type=MlemModel)
    predict = model.model_type.methods["predict"]
    desciptor = InterfaceDescriptor(version="", methods={
        "kek": Signature(name="kek",
                         args=[Argument(name="lol", type_=predict.args[0].type_)],
                         returns=predict.returns)
    })
    serve("sklearn", FastAPIServer(interface=desciptor), standardize=False)


if __name__ == '__main__':
    main()
```

Need to check how this will work for builds/deployments

closes #445

### CODE REVIEW

**Comment by madhur-tandon** [comment]
Is this still WIP? If yes, it is better to indicate in `title` :P

**Comment by mike0sv** [comment]
It's a WIP because I need your feedback to continue :)

**Comment by madhur-tandon** [comment]
Will review today

**Comment by aguschin** [comment]
@mike0sv, thanks for the example - it was VERY helpful.

Tried your script, how it works looks good to me.
1. Unifying endpoints is not something we got requests for yet, so keeping it simple (2 endpoints instead of 4 makes sense to me). I know I suggested this in the very beginning 😅 , so maybe strange to hear this from me, but simple and straighforward is better here IMO - and then we can improve.
2. For this very reason I don't have any feedback about `InterfaceDescriptor` - let's wait until someone use it and then we can improve.
3. Will `serve("sklearn", "fastapi", standardize=True)` rename the endpoint as well? (not only arguments)
4. `serve("sklearn", FastAPIServer(interface=desciptor), standardize=True)` - it uses custom interface even `standardize=True` - confusing to me. Should throw away some error maybe? Or standardize stuff (was assuming the flag gets priority here TBH, but maybe someone else can assume otherwise).

**Comment by mike0sv** [comment]
3. Yes
4. I use "more granular setting takes preference", so flag is overrided by custom server signature. We can add this to the docstring
5. Actually, it might be better to move this field to Server class so it can be configured "permanently"

**Comment by aguschin** [comment]
> Actually, it might be better to move this field to Server class so it can be configured "permanently"

Yes, that makes sense to me!

**Comment by aguschin** [comment]
Hmm, tests pass, but when trying to run your code snippet from the first message, I get this:

<details>

```shell
INFO:     127.0.0.1:59115 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/applications.py", line 225, in openapi
    return JSONResponse(self.openapi())
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/applications.py", line 200, in openapi
    self.openapi_schema = get_openapi(
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 423, in get_openapi
    definitions = get_model_definitions(
  File "/Users/aguschin/.local/share/virtualenvs/mlem-Utz6DvOn/lib/python3.10/site-packages/fastapi/utils.py", line 45, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 461, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 922, in pydantic.schema.field_singleton_schema
KeyError: <class 'pydantic.main.DataFrameRow'>
```

</details>

image

`pydantic==1.10.2`

This is for both old models (4 methods for iris classifier) and new (2 methods).

**Comment by aguschin** [comment]
just fyi, the problem is still there)

**Comment by mike0sv** [comment]
That was wrongdoings of #469 :)

**Review by aguschin — APPROVED** [review]
Works now! Cool! Please merge if you don't plan to implement anything else.

**Pull request merged**
