### PR TITLE
Checking flyio org PR didn't break anything

### PR DESCRIPTION
**Pull request by aguschin**
@aminalaee, when you change GH workflow in a PR, GH runs the workflow from the `base` branch. So, we couldn't test your changes. This is not recommended OFC, but I didn't found a good way to check them on your PR (usually I create a dummy branch that changes README or something, and set `base` for it to be feature branch that changes workflow). So I merged, since your PR LGTM, and in this PR we're actually checking it didn't break anything 😄

### CODE REVIEW

**Comment by aminalaee** [comment]
Hmm...strange. Is it failing now because of flyctl?

**Comment by aguschin** [comment]
Nope, `authorize` job failed yesterday - not sure what was the cause. Re-run the job, it passed, now let's see how other jobs finish.

**Comment by aminalaee** [comment]
Now it failed, I think the reasons were:
- I should rename the test to `test_flyio_create_app`
- And in the GH action it should be `pytest -k flyio` not flyctl 🤦 
- And not sure if flyctl should be added to the $PATH or it will work out of the box after install

**Comment by aguschin** [comment]
Ok, no problem @aminalaee. Let me give you rights to write to this repo, so we can test it properly now, without merging things in `main` first. I sent you an invite. Can you create a branch with fix **in this repo** (not using your fork), and make a PR to `main`? Then I'll create a dummy branch to be "merged" in your branch, and there we'll see how CI finishes.

**Comment by aminalaee** [comment]
Ok sure, @aguschin Thanks

**Pull request closed without merging**
