### PR TITLE
Fix `setup.py` classifiers

### PR DESCRIPTION
**Pull request by aguschin**

### CODE REVIEW

**Comment by mike0sv** [comment]
Should we also exclude 3.7?

**Comment by aguschin** [comment]
@skshetry, in which projects do we use it?

**Comment by aguschin** [comment]
@mike0sv, excluded 3.7.

**Comment by skshetry** [comment]
@aguschin, all of the packages mentioned in https://github.com/iterative/status#other-projects + `dql`.

**Comment by aguschin** [comment]
Thanks @skshetry! Why don't you use it in DVC?

**Comment by skshetry** [comment]
No strong reason tbh. All of those packages came after we had a good template, and we keep `dvc` in a good enough shape.

There are minor things like `.md` vs `.rst` debate (dvc mixes both, template uses rst), and `src/` based directories that template forces (which we are okay with in dvc).

**Review by mike0sv — CHANGES_REQUESTED** [review]
Change heroku tests to run on 3.8

**Comment by aguschin** [comment]
Fixed. I guess we should consider moving control over another if-else conditions based on OS and Python (I saw some docker tests that are controlled in code) to GHA workflow as well. WDYT @mike0sv?

**Comment by mike0sv** [comment]
Maybe, let's do it in another housekeeping issue

**Comment by aguschin** [comment]
@mike0sv, you can approve and merge.
checked this works in https://github.com/iterative/mlem/pull/491

**Review by mike0sv — APPROVED** [review]

**Pull request merged**
