### PR TITLE
Enable rev option for local git repos

### PR DESCRIPTION
**Pull request by mike0sv**

### CODE REVIEW

**Comment by mike0sv** [comment]
So tests failed because pygit2 is not installed. I think we can just add it to install_requires, but there is other option to make it extra, so you will be able to use this feature only if pygit2 installed. @aguschin WDYT?

**Comment by aguschin** [comment]
👍🏻 
I think adding it to install_requries is valid, since this is a "built-in" functionality for MLEM (compared to let's say fastapi serving).

**Comment by aguschin** [comment]
Some tests fail @mike0sv

**Review by aguschin — APPROVED** [review]

**Comment by mike0sv** [comment]
I dont have access to windows machine RN, will check when I do

**Comment by mike0sv** [comment]
It seems that for now the only way is to xfail those tests for windows because of https://github.com/fsspec/filesystem_spec/issues/1125

**Review by aguschin — APPROVED** [review]

**Pull request merged**
