### PR TITLE
change emoji  from  💅 to 🖇️

### PR DESCRIPTION
**Pull request by aguschin**
Replaces
```shell
$ mlem serve tmp/torch_model fastapi
⏳️ Loading model from tmp/torch_model.mlem
Starting fastapi server...
💅 Adding route for /predict
💅 Adding route for /torch_predict
Checkout openapi docs at <http://0.0.0.0:8080/docs>
INFO:     Started server process [15323]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```
with
```shell
$ mlem serve tmp/torch_model fastapi
⏳️ Loading model from tmp/torch_model.mlem
Starting fastapi server...
🖇️ Adding route for /predict
🖇️ Adding route for /torch_predict
Checkout openapi docs at <http://0.0.0.0:8080/docs>
INFO:     Started server process [15346]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

### CODE REVIEW

**Comment by mike0sv** [comment]
NOOOOOOOOOO

**Comment by aguschin** [comment]
Can't merge without your approval, @mike0sv 😢

**Comment by aguschin** [comment]
OK, who am I kidding with? Of course, I can!

**Comment by mike0sv** [comment]
😢

**Pull request merged**
